### ISSUE TITLE
Add support for rotating and changing oxd server certificates and keys

### ISSUE THREAD

**Issue by moabu** [GluuFederation/docker-certmanager#2]
Rotate and change oxd-server application and admin keystore.

defaults:

```bash
APPLICATION_KEYSTORE_PATH=/opt/oxd-server/conf/oxd-server.keystore
APPLICATION_KEYSTORE_PASSWORD_FILE=/etc/gluu/conf/app_keystore_password
ADMIN_KEYSTORE_PATH=/opt/oxd-server/conf/oxd-server.keystore
ADMIN_KEYSTORE_PASSWORD_FILE=/etc/gluu/conf/admin_keystore_password
/etc/certs/application.key
/etc/certs/application.crt
/etc/certs/admin.key
/etc/certs/admin.crt
```

**Comment by iromli** [comment]
Implemented in d9de0a83a943855705b540722ebc484a6a563b9f

**Comment by moabu** [comment]
Although the certificates seem to be generated by the job it doesn't seem like its updated in the oxd container

```
INFO - certmanager - 2020-06-26 10:07:00,946 - Processing updates for service oxd
INFO - certmanager - 2020-06-26 10:07:00,946 - Generating new /etc/certs/oxd_application.crt and /etc/certs/oxd_application.key file(s)
INFO - certmanager - 2020-06-26 10:07:01,145 - Generating new /etc/certs/oxd_application.keystore file
INFO - certmanager - 2020-06-26 10:07:01,238 - Generating new /etc/certs/oxd_admin.crt and /etc/certs/oxd_admin.key file(s)
INFO - certmanager - 2020-06-26 10:07:01,416 - Generating new /etc/certs/oxd_admin.keystore file
```

**Comment by iromli** [comment]
Have you re-deployed oxd?

**Comment by moabu** [comment]
re-deploying oxd gives back an error in key password.

```bash
INFO - pygluu.containerlib.wait - 2020-07-01 16:27:53,775 - Config is ready
INFO - pygluu.containerlib.wait - 2020-07-01 16:27:53,793 - Secret is ready
INFO - pygluu.containerlib.wait - 2020-07-01 16:27:54,098 - LDAP is ready
BASEDIR=/opt/oxd-server/bin
CONF=/opt/oxd-server/bin/../conf/oxd-server.yml
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
INFO  [2020-07-01 16:27:57,062] io.dropwizard.server.DefaultServerFactory: Registering jersey handler with root path prefix: /
INFO  [2020-07-01 16:27:57,065] io.dropwizard.server.DefaultServerFactory: Registering admin handler with root path prefix: /
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$2 (file:/opt/oxd-server/lib/oxd-server.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$2
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
INFO  [2020-07-01 16:27:57,238] org.gluu.oxd.server.ServerLauncher: Starting service configuration...
INFO  [2020-07-01 16:27:57,241] org.gluu.oxd.server.ServerLauncher: commit: ea70947acf436ab86556aa03b2c2b496f30d156f, branch: origin/master, build time:10.06.2020 @ 08:47:55 UTC
INFO  [2020-07-01 16:27:57,349] org.gluu.oxd.server.ServerLauncher: Configuration: OxdServerConfiguration{, registerClientAppType='web', registerClientResponesType='code', useClientAuthenticationForPat=true, trustAllCerts=false, keyStorePath='', keyStorePassword='', cryptProviderKeyStorePath='', cryptProviderKeyStorePassword='', cryptProviderDnName='', supportGoogleLogout=true, stateExpirationInMinutes=5, nonceExpirationInMinutes=5, dbCleanupIntervalInHours=1, rpCacheExpirationInMinutes=60, publicOpKeyCacheExpirationInMinutes=60, protectCommandsWithAccessToken=true, acceptIdTokenWithoutSignature=false, uma2AuthRegisterClaimsGatheringEndpointAsRedirectUriOfClient=false, migrationSourceFolderPath='', storage='gluu_server_configuration', storageConfiguration={"baseDn":"o=gluu","connection":"/etc/gluu/conf/gluu-ldap.properties","salt":"/etc/gluu/conf/salt","type":"/etc/gluu/conf/gluu.properties"}', defaultSiteConfig={"access_token_as_jwt":false,"access_token_lifetime":null,"access_token_signing_alg":"","acr_values":[""],"authorized_origins":[],"claims_locales":["en"],"claims_redirect_uri":[],"client_id":"","client_jwks_uri":"","client_name":"","client_secret":"","client_uri":"","contacts":[],"custom_attributes":{},"default_max_age":null,"front_channel_logout_session_required":false,"front_channel_logout_uris":[],"grant_type":["authorization_code"],"id_token_binding_cnf":"","id_token_encrypted_response_alg":"","id_token_encrypted_response_enc":"","id_token_signed_response_alg":"","initiate_login_uri":"","jwks":"","logo_uri":"","logout_redirect_uris":[],"op_configuration_endpoint":"","policy_uri":"","redirect_uris":[],"request_object_encryption_alg":"","request_object_encryption_enc":"","request_object_signing_alg":"","request_uris":[],"require_auth_time":false,"response_types":["code"],"rpt_as_jwt":false,"run_introspection_script_beforeaccess_token_as_jwt_creation_and_include_claims":false,"scope":["openid","profile","email"],"sector_identifier_uri":"","software_id":"","software_statement":"","software_version":"","tls_client_auth_subject_dn":"","token_endpoint_auth_method":"","token_endpoint_auth_signing_alg":"","tos_uri":"","trusted_client":false,"ui_locales":["en"],"user_info_encrypted_response_alg":"","user_info_encrypted_response_enc":"","user_info_signed_response_alg":""}', allowedOpHosts=[]', addClientCredentialsGrantTypeAutomaticallyDuringClientRegistration=true, proxyConfiguration=null', idTokenValidationCHashRequired=true', idTokenValidationAtHashRequired=true', validateUserInfoWithIdToken=false', protectCommandsWithOxdId=[]', persistenceManagerRemoveCount=1000'}
INFO  [2020-07-01 16:27:57,552] org.gluu.persist.ldap.operation.impl.LdapConnectionProvider: Attempting to create connection pool: 1
INFO  [2020-07-01 16:27:57,745] org.gluu.persist.ldap.operation.impl.LdapConnectionProvider: Attempting to create connection pool: 1
INFO  [2020-07-01 16:27:57,917] org.gluu.persist.ldap.impl.LdapEntryManagerFactory: Created LdapEntryManager: org.gluu.persist.ldap.operation.impl.LdapOperationServiceImpl@1a256d80
INFO  [2020-07-01 16:27:57,973] org.gluu.oxd.server.ServerLauncher: oxD Services are configured successfully.
INFO  [2020-07-01 16:27:57,979] io.dropwizard.server.ServerFactory: Starting OxdServerApplication
INFO  [2020-07-01 16:27:58,066] org.eclipse.jetty.setuid.SetUIDListener: Opened application@7ccfdaef{SSL,[ssl, http/1.1]}{0.0.0.0:8443}
INFO  [2020-07-01 16:27:58,066] org.eclipse.jetty.setuid.SetUIDListener: Opened admin@a6e4897{SSL,[ssl, http/1.1]}{0.0.0.0:8444}
INFO  [2020-07-01 16:27:58,068] org.eclipse.jetty.server.Server: jetty-9.4.24.v20191120; built: 2019-11-20T21:37:49.771Z; git: 363d5f2df3a8a28de40604320230664b9c793c16; jvm 11.0.7+10
ERROR [2020-07-01 16:27:58,080] io.dropwizard.cli.ServerCommand: Unable to start server, shutting down
! java.security.UnrecoverableKeyException: failed to decrypt safe contents entry: javax.crypto.BadPaddingException: Given final block not properly padded. Such issues can arise if a bad key is used during decryption.
! ... 20 common frames omitted
! Causing: java.io.IOException: keystore password was incorrect
! at java.base/sun.security.pkcs12.PKCS12KeyStore.engineLoad(Unknown Source)
! at java.base/sun.security.util.KeyStoreDelegator.engineLoad(Unknown Source)
! at java.base/java.security.KeyStore.load(Unknown Source)
! at org.eclipse.jetty.util.security.CertificateUtils.getKeyStore(CertificateUtils.java:54)
! at org.eclipse.jetty.util.ssl.SslContextFactory.loadKeyStore(SslContextFactory.java:1188)
! at org.eclipse.jetty.util.ssl.SslContextFactory.load(SslContextFactory.java:323)
! at org.eclipse.jetty.util.ssl.SslContextFactory.doStart(SslContextFactory.java:245)
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
! at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
! at org.eclipse.jetty.server.Server.start(Server.java:407)
! at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
! at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:100)
! at org.eclipse.jetty.server.Server.doStart(Server.java:371)
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
! at io.dropwizard.cli.ServerCommand.run(ServerCommand.java:53)
! at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:45)
! at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
! at io.dropwizard.cli.Cli.run(Cli.java:79)
! at io.dropwizard.Application.run(Application.java:94)
! at org.gluu.oxd.server.OxdServerApplication.main(OxdServerApplication.java:23)
java.io.IOException: keystore password was incorrect
        at java.base/sun.security.pkcs12.PKCS12KeyStore.engineLoad(Unknown Source)
        at java.base/sun.security.util.KeyStoreDelegator.engineLoad(Unknown Source)
        at java.base/java.security.KeyStore.load(Unknown Source)
        at org.eclipse.jetty.util.security.CertificateUtils.getKeyStore(CertificateUtils.java:54)
        at org.eclipse.jetty.util.ssl.SslContextFactory.loadKeyStore(SslContextFactory.java:1188)
        at org.eclipse.jetty.util.ssl.SslContextFactory.load(SslContextFactory.java:323)
        at org.eclipse.jetty.util.ssl.SslContextFactory.doStart(SslContextFactory.java:245)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
        at org.eclipse.jetty.server.Server.start(Server.java:407)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:100)
        at org.eclipse.jetty.server.Server.doStart(Server.java:371)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
        at io.dropwizard.cli.ServerCommand.run(ServerCommand.java:53)
        at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:45)
        at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
        at io.dropwizard.cli.Cli.run(Cli.java:79)
        at io.dropwizard.Application.run(Application.java:94)
        at org.gluu.oxd.server.OxdServerApplication.main(OxdServerApplication.java:23)
Caused by: java.security.UnrecoverableKeyException: failed to decrypt safe contents entry: javax.crypto.BadPaddingException: Given final block not properly padded. Such issues can arise if a bad key is used during decryption.
        ... 20 more
```

**Comment by iromli** [comment]
Let me double check ...

**Comment by iromli** [comment]
@moabu 

> re-deploying oxd gives back an error in key password after rotating keys.

Please try again using latest dev image (you may need to pull the updates).

**Comment by moabu** [comment]
fixed in commit https://github.com/GluuFederation/docker-certmanager/commit/e1f8ab038a4d155c7b0dca569ce5749b38d96523. 

Thanks @iromli
